allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - '@prisma/engines'
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/client'
  - prisma
  - protobufjs
